@startuml
allowmixing

rectangle "User Interface Layer" {
	package interfaces {
		package web {
			class SubscriptionController
		}
	}
}

rectangle "Application Layer" {
	package application {
		package dto {
			class SubscriptionDto
		}

		package facade {
			interface SubscriptionFacade
			class SubscriptionCommand
			class SubscriptionFacadeImpl

		}
	}
}

rectangle "Domain Model Layer" {
	package domain {
		package entity {
			class Subscription
		}

		package input {
			interface SubscriptionService
		}

		package service {
			class SubscriptionServiceImpl
		}

		package output {
			interface SubscriptionPersistencePort
		}
	}
}

rectangle "Infrastructure Layer" {
	package infrastructure {
		package persistence {
			package jpa {
				class JpaSubscriptionPersistenceAdapter
				class SubscriptionPersistenceJpaRepository
				class SubscriptionPersistence
			}
		}
	}
}

actor User
User -down-> SubscriptionController

SubscriptionController -down-> SubscriptionFacade
SubscriptionController .down.> SubscriptionCommand: uses
SubscriptionController .down.> SubscriptionDto: uses

SubscriptionFacade .left.> SubscriptionCommand: uses
SubscriptionFacade .right.> SubscriptionDto: uses
SubscriptionFacadeImpl -up-> SubscriptionFacade: implements
SubscriptionFacadeImpl .up.> SubscriptionCommand: uses
SubscriptionFacadeImpl .up.> SubscriptionDto: uses

SubscriptionFacadeImpl -down-> SubscriptionService

SubscriptionServiceImpl -up-> SubscriptionService: implements
SubscriptionServiceImpl -down-> SubscriptionPersistencePort
SubscriptionService ..> Subscription: uses
SubscriptionServiceImpl ..> Subscription: uses

SubscriptionPersistencePort .left.> Subscription: uses
JpaSubscriptionPersistenceAdapter .up.> Subscription: uses

JpaSubscriptionPersistenceAdapter -up-> SubscriptionPersistencePort: implements
JpaSubscriptionPersistenceAdapter -left-> SubscriptionPersistenceJpaRepository
SubscriptionPersistenceJpaRepository ..> SubscriptionPersistence: uses
JpaSubscriptionPersistenceAdapter ..> SubscriptionPersistence: uses

@enduml