@startuml
allowmixing

rectangle "Application Layer" {
	package application {
		package web {
			class SubscriptionController
			class SubscriptionCommand
			class SubscriptionDto
		}
	}
}

rectangle "Domain Model Layer" {
	package domain {
		package model {
			package subscrition {
				class Subscription
				interface SubscriptionRepository
			}
		}
		package service {
			interface SubscriptionService
			package impl {
				class SubscriptionServiceImpl
			}
		}
	}
}

rectangle "Infrastructure Layer" {
	package infrastructure {
		package persistence {
			package jpa {
				class JpaSubscriptionRepository
				class SubscriptionPersistenceRepository
				class SubscriptionPersistence
			}
		}
	}
}

actor User
User -down-> SubscriptionController

SubscriptionController .left.> SubscriptionCommand: uses
SubscriptionController .right.> SubscriptionDto: uses

SubscriptionController -down-> SubscriptionService
SubscriptionServiceImpl -up-> SubscriptionService: implements

SubscriptionServiceImpl ..> Subscription: uses
SubscriptionRepository .left.> Subscription: uses
JpaSubscriptionRepository .up.> Subscription: uses

SubscriptionServiceImpl -down-> SubscriptionRepository
JpaSubscriptionRepository -up-> SubscriptionRepository: implements
JpaSubscriptionRepository -left-> SubscriptionPersistenceRepository
SubscriptionPersistenceRepository ..> SubscriptionPersistence: uses
JpaSubscriptionRepository ..> SubscriptionPersistence: uses

@enduml