@startuml
allowmixing

rectangle "Input/Driving/Primary Adapter" {
	package inputadapter {
		package web {
			class SubscriptionController
		}
	}
}

rectangle "Application" {
	package application {
		package inputport {
			interface CreateSubscriptionUseCasePort
		}

		package core {
			class Subscription
			package usecase {
				class CreateSubscriptionUseCase
			}
		}

		package outputport {
			interface SubscriptionPersistencePort
		}
	}
}

rectangle "Output/Driven/Secondary Adapter" {
	package outputadapter {
		package persistence {
			package jpa {
				class JpaSubscriptionPersistenceAdapter
				class SubscriptionPersistenceJpaRepository
				class SubscriptionPersistence
			}
		}
	}
}

actor User
User -down-> SubscriptionController

SubscriptionController -down-> CreateSubscriptionUseCasePort
CreateSubscriptionUseCasePort .down.> Subscription: uses
CreateSubscriptionUseCase -up-> CreateSubscriptionUseCasePort: implements
CreateSubscriptionUseCase .left.> Subscription: uses
CreateSubscriptionUseCase .down.> SubscriptionPersistencePort: uses

SubscriptionPersistencePort .up.> Subscription: uses

JpaSubscriptionPersistenceAdapter -up-> SubscriptionPersistencePort: implements
JpaSubscriptionPersistenceAdapter -left-> SubscriptionPersistenceJpaRepository
SubscriptionPersistenceJpaRepository ..> SubscriptionPersistence: uses
JpaSubscriptionPersistenceAdapter ..> SubscriptionPersistence: uses

@enduml