@startuml
allowmixing

rectangle "Input/Driving/Primary Adapter" {
	package inputadapter {
		package web {
			class SubscriptionController
		}
	}
}

rectangle "Application Core" {
	package application { 
		package usecase {
			class CreateSubscriptionUseCase
		}
	
		package inputport {
			interface CreateSubscriptionUseCasePort
		}

		package outputport {
			interface CreateSubscriptionPersistencePort
			interface QuerySubscriptionPersistencePort
		}
	}
	package domain { 
		class Subscription
		class EmailAddress
	}
}

rectangle "Output/Driven/Secondary Adapter" {
	package outputadapter {
		package persistence {
			package jpa {
				class SubscriptionJpaPersistenceAdapter
				class SubscriptionJpaRepository
				class SubscriptionJpaEntity
			}
		}
	}
}

actor User
User -down-> SubscriptionController

SubscriptionController -down-> CreateSubscriptionUseCasePort
CreateSubscriptionUseCasePort .down.> Subscription: uses
CreateSubscriptionUseCase -up-> CreateSubscriptionUseCasePort: implements
CreateSubscriptionUseCase .left.> Subscription: uses
CreateSubscriptionUseCase .down.> CreateSubscriptionPersistencePort: uses
CreateSubscriptionUseCase .down.> QuerySubscriptionPersistencePort: uses

CreateSubscriptionPersistencePort .up.> Subscription: uses
QuerySubscriptionPersistencePort .up.> Subscription: uses

SubscriptionJpaPersistenceAdapter -up-> CreateSubscriptionPersistencePort: implements
SubscriptionJpaPersistenceAdapter -up-> QuerySubscriptionPersistencePort: implements
SubscriptionJpaPersistenceAdapter -left-> SubscriptionJpaRepository
SubscriptionJpaRepository ..> SubscriptionJpaEntity: uses
SubscriptionJpaPersistenceAdapter ..> SubscriptionJpaEntity: uses

@enduml