@startuml
allowmixing

rectangle "User Interface Layer" {
	package userinterface {
		class SubscriptionFormController
	}
}

rectangle "Application Layer" {
	package application {
		class SubscriptionService
	}
}

rectangle "Domain Layer" {
	package domain {
		class Subscription
	}
}

rectangle "Infrastructure Layer" {

	package infrastructure {
		class SubscriptionRepository
	}
}

actor User

User -down-> SubscriptionFormController
SubscriptionFormController -down-> SubscriptionService
SubscriptionService -down-> SubscriptionRepository

SubscriptionService .down.> Subscription
SubscriptionRepository .left.> Subscription

@enduml