# ----------------------------------------
# APP PROPERTIES
# ----------------------------------------
historia:
  Subscription:
    event:
      kafka-topic: Subscription
      kafka-dlq: Subscription-dlq
  verification:
    event:
      kafka-topic:  verification
      kafka-dlq:  verification-dlq
  iam:
    event:
      kafka-topic: iam
      kafka-dlq: iam-dlq

# ----------------------------------------
# SERVER PROPERTIES
# ----------------------------------------
server: 
  port: 8080
#   servlet: 
#     context-path: /subscribe

logging:
  level:
    root: WARN
    # org.springframework.beans.factory: TRACE
    # org.springframework.beans.factory.support.DefaultListableBeanFactory: DEBUG
    org.springframework.web: ERROR
    com.abchau.historia.subscribe: TRACE
    org.apache.kafka: ERROR
    org.springframework.kafka: OFF
    org.hibernate: ERROR
    io.r2dbc.h2: TRACE

# ----------------------------------------
# SRPING PROPERTIES
# ----------------------------------------
spring:
  main:
    web-application-type: reactive
  output:
    ansi:
      enabled: DETECT

  # ----------------------------------------
  # CORE PROPERTIES
  # ----------------------------------------
  application:
    name: Pizzashop Layered
  debug: true


#   # ----------------------------------------
#   # SRPING DATA R2DBC PROPERTIES
#   # ----------------------------------------
#   datasource:
#     url: jdbc:h2:mem:persondb
#     driverClassName: org.h2.Driver
#     username: sa
#     password: test

#   # only work for servlet
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#       settings:
#         web-allow-others: true
  # ----------------------------------------
  # SRPING DATA JPA PROPERTIES
  # ----------------------------------------
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  # ----------------------------------------
  # SRPING DATA R2DBC PROPERTIES
  # ----------------------------------------
  r2dbc:
    url: r2dbc:h2:mem:///subscribe?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: 
    initialization-mode: always


    # url: ${DB_URL}
    # username: ${DB_USERNAME}
    # password: ${DB_PASSWORD}

  # ----------------------------------------
  # SRPING KAFKA PROPERTIES
  # ----------------------------------------
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # transaction-id-prefix: tx.
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
        spring.json.trusted.packages: "*"
        # isolation.level: read_committed
        spring.json.use.type.headers: false
        # spring.json.value.default.type: 

  # ----------------------------------------
  # WEB PROPERTIES
  # ----------------------------------------
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  # ----------------------------------------
  # SECURITY PROPERTIES
  # ----------------------------------------

  # ----------------------------------------
  # DEV TOOLS
  # ----------------------------------------
  devtools:
    restart:
      enabled: false
      exclude: tatic/**,public/**
# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
management:
  endpoints:
    shutdown:
      enabled: false
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"