DROP TABLE IF EXISTS Subscriptions;
CREATE TABLE IF NOT EXISTS Subscriptions (
	id BINARY(36) PRIMARY KEY,
	email VARCHAR(512) NOT NULL,
	username VARCHAR(512) NOT NULL,
	password VARCHAR(512) NOT NULL,
	status VARCHAR(256) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	last_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
	version BIGINT NOT NULL
);

DROP TABLE IF EXISTS Verifications;
CREATE TABLE IF NOT EXISTS Verifications (
	id BINARY(36) PRIMARY KEY,
	email VARCHAR(512) NOT NULL,
	code VARCHAR(512) NOT NULL,
	enabled BOOLEAN NOT NULL,
	status VARCHAR(256) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	sent_at TIMESTAMP WITH TIME ZONE NULL,
	expired_at TIMESTAMP WITH TIME ZONE NULL,
	verified_at TIMESTAMP WITH TIME ZONE NULL,
	disabled_at TIMESTAMP WITH TIME ZONE NULL,
	version BIGINT NOT NULL
);
