@startuml

actor User
box Presentation Layer
participant SubscriptionController << (C,#ADD1B2) MVC Controller >>
end box
box Business Logic Layer
participant SubscriptionService << (C,#ADD1B2) Service >>
end box
box Data Layer
participant SubscriptionRepository << (C,#ADD1B2) Repository >>
end box
database Datastore

activate User

User --> SubscriptionController
activate SubscriptionController

note over SubscriptionRepository: sometimes via this

SubscriptionController --> SubscriptionRepository
activate SubscriptionRepository

SubscriptionRepository --> Datastore
activate Datastore

Datastore --> SubscriptionRepository
deactivate Datastore

SubscriptionRepository --> SubscriptionController
deactivate SubscriptionRepository

note over SubscriptionService: sometimes via this

SubscriptionController --> SubscriptionService
activate SubscriptionService

SubscriptionService --> SubscriptionRepository
activate SubscriptionRepository

SubscriptionRepository --> Datastore
activate Datastore

Datastore --> SubscriptionRepository
deactivate Datastore

SubscriptionRepository --> SubscriptionService
deactivate SubscriptionRepository

SubscriptionService --> SubscriptionController
deactivate SubscriptionService

SubscriptionController --> User
deactivate SubscriptionController

@enduml