
=== Domain Driven Design

*Brief Description of Duties & Responsibilities*:

* `*SubscriptionController*`: receives taks from specific interface
* `*SubscriptionServiceFacadeImpl*`: task coordination, transaction, anti-corruption
* `*SubscriptionServiceImpl*`: business logic
* `*JpaSubscriptionRepositoy*`: anti-corruption, delegate persistence operations to `SubscriptionPersistenceJpaRepositoy`
* `*SubscriptionPersistenceJpaRepositoy*`: do technology-specified persistence operations

.Sequence Diagram for DDD Architecture
[plantuml,target=ddd-sequence,format=svg]
....
@startuml

actor User 
box User Interfaces Layer
participant SubscriptionController << (C,#ADD1B2) @Controller >>
end box
box Application Layer
participant SubscriptionServiceFacadeImpl << (C,#ADD1B2) @Bean >>
end box
box Domain Model Layer
participant SubscriptionServiceImpl << (C,#ADD1B2) @Bean >>
end box
box Infrastructure Layer
participant JpaSubscriptionRepository << (C,#ADD1B2) @Bean >>
participant SubscriptionPersistenceJpaRepository << (C,#ADD1B2) @Repository >>
end box
database Datastore

activate User

User --> SubscriptionController
activate SubscriptionController

note over SubscriptionServiceFacadeImpl: via SubscriptionServiceFacade

SubscriptionController --> SubscriptionServiceFacadeImpl
activate SubscriptionServiceFacadeImpl

note over SubscriptionServiceImpl: via SubscriptionService

SubscriptionServiceFacadeImpl --> SubscriptionServiceImpl
activate SubscriptionServiceImpl

note over JpaSubscriptionRepository: via SubscriptionRepository

SubscriptionServiceImpl --> JpaSubscriptionRepository
activate JpaSubscriptionRepository

note over SubscriptionPersistenceJpaRepository: via pring data repository

JpaSubscriptionRepository --> SubscriptionPersistenceJpaRepository
activate SubscriptionPersistenceJpaRepository

SubscriptionPersistenceJpaRepository --> Datastore
activate Datastore

Datastore --> SubscriptionPersistenceJpaRepository
deactivate Datastore

SubscriptionPersistenceJpaRepository --> JpaSubscriptionRepository
deactivate SubscriptionPersistenceJpaRepository

JpaSubscriptionRepository --> SubscriptionServiceImpl
deactivate JpaSubscriptionRepository

SubscriptionServiceImpl --> SubscriptionServiceFacadeImpl
deactivate SubscriptionServiceImpl

SubscriptionServiceFacadeImpl --> SubscriptionController
deactivate SubscriptionServiceFacadeImpl

SubscriptionController --> User
deactivate SubscriptionController
....

.Class Diagram for DDD Architecture
[plantuml,target=ddd-class,format=svg]
....
@startuml
allowmixing

rectangle "User Interfaces Layer" {
	package interfaces {
		package web {
			class SubscriptionController
		}
	}
}

rectangle "Application Layer" {
	package application {
		interface SubscriptionFacade
		class SubscriptionCommand

		package impl2 as "impl" {
			class SubscriptionFacadeImpl
		}
		package dto {
			class SubscriptionDto
		}
	}
}

rectangle "Domain Model Layer" {
	package domain {
		package model {
			package subscrition {
				class Subscription
				interface SubscriptionRepository
			}
		}
		package service {
			interface SubscriptionService
			package impl {
				class SubscriptionServiceImpl
			}
		}
	}
}

rectangle "Infrastructure Layer" {
	package infrastructure {
		package persistence {
			package jpa {
				class JpaSubscriptionRepository
				class SubscriptionPersistenceRepository
				class SubscriptionPersistence
			}
		}
	}
}

actor Http
Http -down-> SubscriptionController

SubscriptionController --> SubscriptionFacade
SubscriptionFacadeImpl -up-> SubscriptionFacade: implements
SubscriptionController .down.> SubscriptionCommand: uses
SubscriptionFacade .left.> SubscriptionCommand: uses
SubscriptionFacadeImpl .up.> SubscriptionCommand: uses
SubscriptionController .down.> SubscriptionDto: uses
SubscriptionFacade .right.> SubscriptionDto: uses
SubscriptionFacadeImpl .up.> SubscriptionDto: uses

SubscriptionFacadeImpl -down-> SubscriptionService
SubscriptionServiceImpl -up-> SubscriptionService: implements

SubscriptionServiceImpl ..> Subscription: uses
SubscriptionRepository .left.> Subscription: uses
JpaSubscriptionRepository .up.> Subscription: uses

SubscriptionServiceImpl -down-> SubscriptionRepository
JpaSubscriptionRepository -up-> SubscriptionRepository: implements
JpaSubscriptionRepository -left-> SubscriptionPersistenceRepository
SubscriptionPersistenceRepository ..> SubscriptionPersistence: uses
JpaSubscriptionRepository ..> SubscriptionPersistence: uses

@enduml
....