@startuml
allowmixing

rectangle "User Interfaces Layer" {
	package userinterface {
		class SubscriptionFormController
	}
}

rectangle "Application Layer" {
	package application {
		interface SubscriptionFacade
		class CreateSubscriptionCommand
		class SubscriptionFacadeImpl
	}
}

rectangle "Domain Model Layer" {
	package domain {
		class Subscription
		interface SubscriptionRepository
	}
}

rectangle "Infrastructure Layer" {
	package infrastructure {
		class SubscriptionJpaPersistenceAdapter
		class SubscriptionJpaRepository
		class SubscriptionJpaEntity
	}
}

actor User
User -down-> SubscriptionFormController

SubscriptionFormController --> SubscriptionFacade
SubscriptionFacadeImpl -up-> SubscriptionFacade: implements
SubscriptionFormController .down.> CreateSubscriptionCommand: uses
SubscriptionFacade .left.> CreateSubscriptionCommand: uses
SubscriptionFacadeImpl .up.> CreateSubscriptionCommand: uses

SubscriptionFacadeImpl ..> Subscription: uses
SubscriptionRepository .left.> Subscription: uses
SubscriptionJpaPersistenceAdapter .up.> Subscription: uses

SubscriptionFacadeImpl -down-> SubscriptionRepository
SubscriptionJpaPersistenceAdapter -up-> SubscriptionRepository: implements
SubscriptionJpaPersistenceAdapter -left-> SubscriptionJpaRepository
SubscriptionJpaRepository ..> SubscriptionJpaEntity: uses
SubscriptionJpaPersistenceAdapter ..> SubscriptionJpaEntity: uses

@enduml