:imagesdir: images

== 3-tier Architecture

*Brief Description of Duties & Responsibilities*:

* `*SubscriptionController*`: receives taks from specific interface but...
* `*SubscriptionServiceImpl*`: do business logic
* `*SubscriptionRepositoy*`: do technology-specified persistence operations

.Sequence Diagram for 3-tier Architecture
[plantuml,target=3-tier-sequence,format=svg]
....
@startuml

actor User 
box Presentation Layer
participant SubscriptionController << (C,#ADD1B2) @Controller >>
end box
box Business Logic Layer
participant SubscriptionService << (C,#ADD1B2) @Bean >>
end box
box Data Layer
participant SubscriptionRepository << (C,#ADD1B2) @Repository >>
end box
database Datastore

activate User

User --> SubscriptionController
activate SubscriptionController

note over SubscriptionService: always here

SubscriptionController --> SubscriptionService
activate SubscriptionService

SubscriptionService --> SubscriptionRepository
activate SubscriptionRepository

SubscriptionRepository --> Datastore
activate Datastore

Datastore --> SubscriptionRepository
deactivate Datastore

SubscriptionRepository --> SubscriptionService
deactivate SubscriptionRepository

SubscriptionService --> SubscriptionController
deactivate SubscriptionService

SubscriptionController --> User
deactivate SubscriptionController
....

.Class Diagram for 3-tier Architecture
[plantuml,target=3-tier-class,format=svg]
....
@startuml
allowmixing

rectangle "Presentation Layer" {
	package controller {
		class SubscriptionController
		class SubscriptionDto
	}
}

rectangle "Business Logic Layer" {
	package service {
		class SubscriptionService
	}
}

rectangle "Data Layer" {
	package model {
		class Subscription
	}

	package repository {
		class SubscriptionRepository
	}
}

actor Http

Http -down-> SubscriptionController
SubscriptionController .left.> SubscriptionDto: uses
SubscriptionController -down-> SubscriptionService
SubscriptionService -down-> SubscriptionRepository

SubscriptionService .down.> Subscription
SubscriptionRepository .left.> Subscription

@enduml
....