DROP SEQUENCE IF EXISTS seq_subscriptions_id;
CREATE SEQUENCE seq_subscriptions_id
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

DROP TABLE IF EXISTS subscriptions;
CREATE TABLE IF NOT EXISTS subscriptions (
	id BINARY(36) PRIMARY KEY,
	email VARCHAR(512) NOT NULL,
	status VARCHAR(256) NOT NULL,
	subscribed_at TIMESTAMP WITH TIME ZONE NOT NULL,
	confirmed_at TIMESTAMP WITH TIME ZONE NOT NULL,
	version BIGINT NOT NULL
);
