server: 
  port: 8080
logging:
  level:
    root: INFO
    com.abchau.archexamples.ddd.subscribe: DEBUG
spring:
  output:
    ansi:
      enabled: DETECT
  application:
    name: DDD Architecture
  debug: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect