@startuml
allowmixing

rectangle "Presentation Layer" {
	package controller {
		class SubscriptionController
	}
}

rectangle "Business Logic Layer" {
	package service {
		class SubscriptionService
	}
}

rectangle "Data Layer" {
	package model {
		class Subscription
	}
	package repository {
		class SubscriptionRepository
	}
}

actor Http

Http -down-> SubscriptionController
SubscriptionController -down-> SubscriptionService
SubscriptionController -down-> SubscriptionRepository
SubscriptionService -down-> SubscriptionRepository

SubscriptionController ..> Subscription
SubscriptionService .down.> Subscription
SubscriptionRepository .left.> Subscription

@enduml