@startuml

actor User 
box Input Adapters
participant SubscriptionController << (C,#ADD1B2) @Controller >>
end box
box Application Core
participant CreateSubscriptionUseCase << (C,#ADD1B2) @Bean >>
end box
box Output Adapters
participant SubscriptionJpaPersistenceAdapter << (C,#ADD1B2) @Bean >>
participant SubscriptionJpaRepository << (C,#ADD1B2) @Repository >>
end box
database Datastore

activate User

User --> SubscriptionController
activate SubscriptionController

note over SubscriptionController: via CreateSubscriptionUseCasePort

SubscriptionController --> CreateSubscriptionUseCase
activate CreateSubscriptionUseCase

note over SubscriptionJpaPersistenceAdapter: via SaveSubscriptionPort, \nQueryubscriptionPersistencePort

CreateSubscriptionUseCase --> SubscriptionJpaPersistenceAdapter
activate SubscriptionJpaPersistenceAdapter

SubscriptionJpaPersistenceAdapter --> SubscriptionJpaRepository
activate SubscriptionJpaRepository

SubscriptionJpaRepository --> Datastore
activate Datastore

Datastore --> SubscriptionJpaRepository
deactivate Datastore

SubscriptionJpaRepository --> SubscriptionJpaPersistenceAdapter
deactivate SubscriptionJpaRepository

SubscriptionJpaPersistenceAdapter --> CreateSubscriptionUseCase
deactivate SubscriptionJpaPersistenceAdapter

CreateSubscriptionUseCase --> SubscriptionController
deactivate CreateSubscriptionUseCase

SubscriptionController --> User
deactivate SubscriptionController

@enduml